# permissions for end users to edit crossplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - crossplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - crossplanes/status
  verbs:
  - get
