# permissions for end users to view crossplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - crossplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - crossplanes/status
  verbs:
  - get
